version: "3"
services:
  # Railsアプリケーション
  api:
    container_name: rest-api
    platform: linux/amd64
    build:
      context: .
    volumes:
      - type: bind
        source: ./
        target: /api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:password@db:3306/myapp_development # データベース接続情報

  # MySQLデータベース
  db:
    image: mysql:8.0.26
    container_name: rest-api-db
    platform: linux/amd64
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    ports:
      - "3306:3306"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: rest-api-swagger-ui
    platform: linux/amd64
    environment:
      SWAGGER_JSON: /swagger.json
      PORT: 3001
    volumes:
      - ./app/controllers/api/v1/swagger.json:/swagger.json
    ports:
      - "3001:3001"

volumes:
  mysqldata:
    driver: local
